name: Setup environment
description: Setup environment with dependencies (requires checkout to be done before calling this action)

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4
    - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
      with:
        node-version-file: .tool-versions
        cache: pnpm
    - name: Install dependencies
      run: pnpm install
      shell: bash
