language: node_js
node_js:
  - "node"
cache:
  yarn: true
env:
  # Chrome WebStore ITEM_ID
  - APP_ITEM_ID=gmlbhbdkhnfhhmhdjopdbcfliajcafde
script:
  - yarn test
deploy:
  provider: script
  skip_cleanup: true
  script:
    yarn run build && env WEBSTORE_TOKEN=$(chrome-webstore-manager refresh_token --client_id $CLIENT_ID --client_secret $CLIENT_SECRET --refresh_token $REFRESH_TOKEN) yarn run webstore:update
  on:
    branch: master
    tags: true