language: node_js
node_js:
  - "node"
cache:
  yarn: true
  directories:
    - node_modules
env:
  # Chrome WebStore ITEM_ID
  - APP_ITEM_ID=gmlbhbdkhnfhhmhdjopdbcfliajcafde

stages:
  - test
  - name: GitHub-release
    if: (NOT type IN (pull_request)) AND (branch = master)
  - name: WebStore-publish
    if: (NOT type IN (pull_request)) AND (branch = master)

jobs:
  include:
    # Define test stage
    - script: yarn test
    # Define the GitHub-release stage
    - stage: GitHub-release
      script: skip # Don't re-execute the test.
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn run release-git:ci
    # Define the WebStore-publish stage
    - stage: WebStore-publish
      script: skip # Don't re-execute the test.
      before_deploy:
        # Dynamic generating the ENV variable.
        export WEBSTORE_TOKEN=$(chrome-webstore-manager refresh_token --client_id $CLIENT_ID --client_secret $CLIENT_SECRET --refresh_token $REFRESH_TOKEN)
      deploy:
        provider: script
        skip_cleanup: true
        script:
          yarn run build && yarn run webstore:update && yarn run webstore:publish