language: node_js
node_js:
  - "node"
cache:
  yarn: true
env:
  # Chrome WebStore ITEM_ID
  - APP_ITEM_ID=gmlbhbdkhnfhhmhdjopdbcfliajcafde
script:
  - yarn test
before_deploy:
  script:
    - echo "export WEBSTORE_TOKEN=$(chrome-webstore-manager refresh_token --client_id $CLIENT_ID --client_secret $CLIENT_SECRET --refresh_token $REFRESH_TOKEN)" > token.sh
deploy:
  provider: script
  skip_cleanup: true
  script:
    source token.sh yarn run build && yarn run webstore:update
  on:
    branch: master
    tags: true