// Generated by wxt
export type {};
declare global {
	const ContentScriptContext: typeof import("wxt/client")["ContentScriptContext"];
	const InvalidMatchPattern: typeof import("wxt/sandbox")["InvalidMatchPattern"];
	const MatchPattern: typeof import("wxt/sandbox")["MatchPattern"];
	const browser: typeof import("wxt/browser")["browser"];
	const createIframeUi: typeof import("wxt/client")["createIframeUi"];
	const createIntegratedUi: typeof import("wxt/client")["createIntegratedUi"];
	const createLogger: typeof import("/Users/1natsu/ghq/github.com/1natsu172/Outside-YouTube-Player-Bar/src/utils/logger")["createLogger"];
	const createShadowRootUi: typeof import("wxt/client")["createShadowRootUi"];
	const defineBackground: typeof import("wxt/sandbox")["defineBackground"];
	const defineConfig: typeof import("wxt")["defineConfig"];
	const defineContentScript: typeof import("wxt/sandbox")["defineContentScript"];
	const defineUnlistedScript: typeof import("wxt/sandbox")["defineUnlistedScript"];
	const fakeBrowser: typeof import("wxt/testing")["fakeBrowser"];
	const logger: typeof import("/Users/1natsu/ghq/github.com/1natsu172/Outside-YouTube-Player-Bar/src/utils/logger")["logger"];
	const reCreateLoggerInstance: typeof import("/Users/1natsu/ghq/github.com/1natsu172/Outside-YouTube-Player-Bar/src/utils/logger")["reCreateLoggerInstance"];
	const storage: typeof import("wxt/storage")["storage"];
}
// for type re-export
declare global {
	// @ts-ignore
	export type { Logger } from "/Users/1natsu/ghq/github.com/1natsu172/Outside-YouTube-Player-Bar/src/utils/logger";
	import(
		"/Users/1natsu/ghq/github.com/1natsu172/Outside-YouTube-Player-Bar/src/utils/logger"
	);
	// @ts-ignore
	export type {
		ValueOf,
		NestedValueOf,
	} from "/Users/1natsu/ghq/github.com/1natsu172/Outside-YouTube-Player-Bar/src/utils/typeUtils";
	import(
		"/Users/1natsu/ghq/github.com/1natsu172/Outside-YouTube-Player-Bar/src/utils/typeUtils"
	);
}
