name: Delivery

on:
  push:
    tags:
      - v*

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.tool-versions'
          cache: pnpm
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run delivery
        env:
          EXTENSION_ID: ${{ secrets.GOOGLE_WEBSTORE_EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.GOOGLE_WEBSTORE_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.GOOGLE_WEBSTORE_CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.GOOGLE_WEBSTORE_REFRESH_TOKEN }}
