name: Delivery

on:
  workflow_dispatch:
    inputs:
      dryRun:
        default: false
        type: boolean
        description: Skip submission and perform a dry run
  push:
    tags:
      - v*

env:
  # Use as process.env.SENTRY_AUTH_TOKEN with sentry-vite-plugin
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  testing:
    uses: ./.github/workflows/testing.yml
    secrets: inherit

  delivery:
    runs-on: ubuntu-latest
    needs: [testing]
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version-file: '.tool-versions'
          cache: pnpm
      - name: Install deps
        run: pnpm install
      - name: Create each zips
        run: pnpm run zip
      - name: Submit to stores
        run: pnpm run delivery
        env:
          DRY_RUN: ${{ inputs.dryRun }}
          CHROME_EXTENSION_ID: ${{ secrets.GOOGLE_WEBSTORE_EXTENSION_ID }}
          CHROME_CLIENT_ID: ${{ secrets.GOOGLE_WEBSTORE_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.GOOGLE_WEBSTORE_CLIENT_SECRET }}
          CHROME_REFRESH_TOKEN: ${{ secrets.GOOGLE_WEBSTORE_REFRESH_TOKEN }}
          FIREFOX_EXTENSION_ID: ${{ secrets.FIREFOX_EXTENSION_ID }}
          FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
          FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}
          EDGE_PRODUCT_ID: ${{ secrets.EDGE_PRODUCT_ID }}
          EDGE_CLIENT_ID: ${{ secrets.EDGE_CLIENT_ID }}
          EDGE_CLIENT_SECRET: ${{ secrets.EDGE_CLIENT_SECRET }}
          EDGE_ACCESS_TOKEN_URL: ${{ secrets.EDGE_ACCESS_TOKEN_URL }}
