name: Run Tests

on:
  workflow_call:
  workflow_dispatch:
  pull_request:

env:
  # Use as process.env.SENTRY_AUTH_TOKEN with sentry-vite-plugin
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version-file: '.tool-versions'
          cache: pnpm
      - name: Install deps
        run: |
          pnpm install
      - name: Check to build passed
        run: pnpm run build
      - name: Check to test passed
        run: pnpm run test
