name: Run Tests

on:
  workflow_call:
  workflow_dispatch:
  pull_request:

env:
  # Use as process.env.SENTRY_AUTH_TOKEN with sentry-vite-plugin
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
        with:
          node-version-file: '.tool-versions'
          cache: pnpm
      - name: Install deps
        run: pnpm install
      - name: Check to build passed
        run: pnpm run build
      - name: Check to test passed
        run: pnpm run test
